name: Packer
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt update && sudo apt install -y packer

      - name: install vagrant
        run: |
          TMP="$(mktemp)"
          wget -O "$TMP" https://releases.hashicorp.com/vagrant/2.2.10/vagrant_2.2.10_x86_64.deb
          sudo dpkg -i $TMP
        
      - name: packer build packer.json
        run: |
          packer build packer.json
